version: "3"
services:
  app:
    build:
      context: ./backend
    container_name: cafe-management-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
    command: npm start

  frontend:
    build:
      context: ./frontend
    container_name: cafe-management-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    command: npm run dev
    depends_on:
      - app

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
